services:
  junior_feistel:
    image: cybersecnatlab/challenge-jail
    restart: unless-stopped
    init: true
    privileged: true
    volumes:
      - './chall:/home/user/chall:ro'
    ports:
      - '38014:1337'
    environment:
      - 'FLAG=openECSC{4r3_y0u_r34dy_f0r_7h3_n3x7_0n3?_[random 8]}'
      - 'TIMEOUT=600'
