services:
  backend:
    build: ./backend
    restart: unless-stopped
    env_file: "backend/backend.env"
    tmpfs:
      - /tmp
      - /company:mode=777
    networks:
      - challenge

  mongodb:
    image: mongo:7.0
    restart: unless-stopped
    env_file: "backend/mongo.env"
    networks:
      - challenge

  frontend:
    build: ./frontend
    restart: unless-stopped
    env_file: "frontend/frontend.env"
    networks:
      - challenge

  nginx:
    image: nginx:1.25
    environment:
      NGINX_ENVSUBST_OUTPUT_DIR: "/etc/nginx"
      BACKEND_HOST: "backend:80"
      FRONTEND_HOST: "frontend:3000"
    volumes:
      - ./nginx.conf:/etc/nginx/templates/nginx.conf.template
    ports:
      - "80:80"
    networks:
      - challenge

networks:
  challenge:
