/* BEGIN_LEGAL 

Copyright (c) 2024 Intel Corporation

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  
END_LEGAL */
/// @file xed-gen-table-defs.h

// This file was automatically generated.
// Do not edit this file.

#if !defined(XED_GEN_TABLE_DEFS_H)
# define XED_GEN_TABLE_DEFS_H
#define XED_ICLASS_NAME_STR_MAX 142
#define XED_MAX_ATTRIBUTE_COUNT 103
#define XED_MAX_INST_TABLE_NODES 10190
#define XED_MAX_OPERAND_TABLE_NODES 1669
#define XED_MAX_OPERAND_SEQUENCES 10121
#define XED_MAX_REQUIRED_SIMPLE_FLAGS_ENTRIES 101
#define XED_MAX_REQUIRED_COMPLEX_FLAGS_ENTRIES 149
#define XED_MAX_GLOBAL_FLAG_ACTIONS 492
#define XED_MAX_IFORMS_PER_ICLASS 48
#define XED_MAX_REQUIRED_ATTRIBUTES 262
#define XED_MAX_CONVERT_PATTERNS 5
#define XED_MAX_DECORATIONS_PER_OPERAND 3
#define XED_MAX_MAP_VEX  7
#define XED_MAX_MAP_EVEX 7
#endif
