#!/usr/bin/env python3

import logging
import os
from pwn import remote

logging.disable()

sol = "VTJQO-DLQMW-TFHWC-WORCA-KASXL-VTJQO-TZSHK-VTJQO-UCTEY-FKUDR-XIVHN-KASXL-VHGIJ-UJOSC-GQQRF-XIVHN-FKUDR-WORCA-SKKMM-XIVHN-UCTEY-VHGIJ-TFHWC-RYJKP-QXVIN-SKKMM-UJOSC-TFHWC-UCTEY-VTJQO-KASXL-UJOSC-DLQMW-SROAR-SKKMM-TFHWC-GQQRF-FKUDR-EFDSK-QXVIN-TZSHK-RYJKP-VTJQO-ZMYIK-SXKGM-VTJQO-RYJKP-XIVHN-KASXL-VTJQO-VTJQO-XIVHN-FKUDR-RYJKP-FKUDR-WORCA-TZSHK-WORCA-QXVIN-SROAR-DLQMW-GQQRF-VTJQO-TFHWC-TZSHK-EFDSK-UCTEY-SROAR-XIVHN-TZSHK-UJOSC-GQQRF-UJOSC-WORCA-GQQRF-QXVIN-VTJQO-EFDSK-VTJQO-WORCA-TZSHK-VTJQO-GQQRF-TFHWC-ZMYIK-TFHWC-EFDSK-VTJQO-DLQMW-UCTEY-FKUDR-UJOSC-QXVIN-SXKGM-DLQMW-WORCA-UJOSC-UCTEY-UJOSC-GQQRF-SROAR-EFDSK-SXKGM-GQQRF-QXVIN-KASXL-SROAR-UJOSC-VTJQO-UJOSC-SKKMM-DLQMW-ZMYIK-XIVHN-EFDSK-KASXL-QXVIN-XIVHN-VTJQO-SROAR-VTJQO"

# For TCP connection
HOST = os.environ.get("HOST", "back2basics.challs.open.ecsc2024.it")
PORT = int(os.environ.get("PORT", 38008))

r = remote(HOST, PORT)
r.sendline(sol.encode())
print(r.recvlines(3))
