// protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative /path/to/grand-resort.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.22.1
// source: grand-resort.proto

package grand_resort

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoomRequestModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomRequestModel string `protobuf:"bytes,1,opt,name=RoomRequestModel,proto3" json:"RoomRequestModel,omitempty"`
}

func (x *RoomRequestModel) Reset() {
	*x = RoomRequestModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grand_resort_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomRequestModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomRequestModel) ProtoMessage() {}

func (x *RoomRequestModel) ProtoReflect() protoreflect.Message {
	mi := &file_grand_resort_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomRequestModel.ProtoReflect.Descriptor instead.
func (*RoomRequestModel) Descriptor() ([]byte, []int) {
	return file_grand_resort_proto_rawDescGZIP(), []int{0}
}

func (x *RoomRequestModel) GetRoomRequestModel() string {
	if x != nil {
		return x.RoomRequestModel
	}
	return ""
}

type RoomCreationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomCreationResponse string `protobuf:"bytes,1,opt,name=RoomCreationResponse,proto3" json:"RoomCreationResponse,omitempty"`
}

func (x *RoomCreationResponse) Reset() {
	*x = RoomCreationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grand_resort_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomCreationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomCreationResponse) ProtoMessage() {}

func (x *RoomCreationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grand_resort_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomCreationResponse.ProtoReflect.Descriptor instead.
func (*RoomCreationResponse) Descriptor() ([]byte, []int) {
	return file_grand_resort_proto_rawDescGZIP(), []int{1}
}

func (x *RoomCreationResponse) GetRoomCreationResponse() string {
	if x != nil {
		return x.RoomCreationResponse
	}
	return ""
}

type Room struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price       int32  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *Room) Reset() {
	*x = Room{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grand_resort_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_grand_resort_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_grand_resort_proto_rawDescGZIP(), []int{2}
}

func (x *Room) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Room) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Room) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Room) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type RoomList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rooms []*Room `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
}

func (x *RoomList) Reset() {
	*x = RoomList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grand_resort_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomList) ProtoMessage() {}

func (x *RoomList) ProtoReflect() protoreflect.Message {
	mi := &file_grand_resort_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomList.ProtoReflect.Descriptor instead.
func (*RoomList) Descriptor() ([]byte, []int) {
	return file_grand_resort_proto_rawDescGZIP(), []int{3}
}

func (x *RoomList) GetRooms() []*Room {
	if x != nil {
		return x.Rooms
	}
	return nil
}

type BookingInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId    string `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	Nights    int32  `protobuf:"varint,2,opt,name=nights,proto3" json:"nights,omitempty"`
	GuestName string `protobuf:"bytes,3,opt,name=guestName,proto3" json:"guestName,omitempty"`
}

func (x *BookingInfo) Reset() {
	*x = BookingInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grand_resort_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingInfo) ProtoMessage() {}

func (x *BookingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_grand_resort_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingInfo.ProtoReflect.Descriptor instead.
func (*BookingInfo) Descriptor() ([]byte, []int) {
	return file_grand_resort_proto_rawDescGZIP(), []int{4}
}

func (x *BookingInfo) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *BookingInfo) GetNights() int32 {
	if x != nil {
		return x.Nights
	}
	return 0
}

func (x *BookingInfo) GetGuestName() string {
	if x != nil {
		return x.GuestName
	}
	return ""
}

type BookingConfirm struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *BookingConfirm) Reset() {
	*x = BookingConfirm{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grand_resort_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookingConfirm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingConfirm) ProtoMessage() {}

func (x *BookingConfirm) ProtoReflect() protoreflect.Message {
	mi := &file_grand_resort_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingConfirm.ProtoReflect.Descriptor instead.
func (*BookingConfirm) Descriptor() ([]byte, []int) {
	return file_grand_resort_proto_rawDescGZIP(), []int{5}
}

func (x *BookingConfirm) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_grand_resort_proto protoreflect.FileDescriptor

var file_grand_resort_proto_rawDesc = []byte{
	0x0a, 0x12, 0x67, 0x72, 0x61, 0x6e, 0x64, 0x2d, 0x72, 0x65, 0x73, 0x6f, 0x72, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x47, 0x72, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x6f, 0x72,
	0x74, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3e,
	0x0a, 0x10, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x6f, 0x64,
	0x65, 0x6c, 0x12, 0x2a, 0x0a, 0x10, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x52, 0x6f,
	0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x4a,
	0x0a, 0x14, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x14, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x62, 0x0a, 0x04, 0x52, 0x6f,
	0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x22, 0x33,
	0x0a, 0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x05, 0x72, 0x6f,
	0x6f, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x47, 0x72, 0x61, 0x6e,
	0x64, 0x52, 0x65, 0x73, 0x6f, 0x72, 0x74, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x05, 0x72, 0x6f,
	0x6f, 0x6d, 0x73, 0x22, 0x5b, 0x0a, 0x0b, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x69,
	0x67, 0x68, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x69, 0x67, 0x68,
	0x74, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x75, 0x65, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x75, 0x65, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x22, 0x0a, 0x0e, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x72, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6d, 0x73, 0x67, 0x32, 0xc3, 0x02, 0x0a, 0x09, 0x52, 0x65, 0x63, 0x65, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x59, 0x0a, 0x1e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x63, 0x32, 0x31, 0x61,
	0x37, 0x66, 0x35, 0x30, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1d, 0x2e, 0x47,
	0x72, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x6f, 0x72, 0x74, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x00, 0x12, 0x58, 0x0a,
	0x12, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x37, 0x33, 0x39, 0x35, 0x30,
	0x30, 0x32, 0x39, 0x12, 0x1d, 0x2e, 0x47, 0x72, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x6f, 0x72,
	0x74, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x6f, 0x64,
	0x65, 0x6c, 0x1a, 0x21, 0x2e, 0x47, 0x72, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x6f, 0x72, 0x74,
	0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x09, 0x6c, 0x69, 0x73, 0x74, 0x52,
	0x6f, 0x6f, 0x6d, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x15, 0x2e, 0x47,
	0x72, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x6f, 0x72, 0x74, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x4c,
	0x69, 0x73, 0x74, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x08, 0x62, 0x6f, 0x6f, 0x6b, 0x52, 0x6f, 0x6f,
	0x6d, 0x12, 0x18, 0x2e, 0x47, 0x72, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x6f, 0x72, 0x74, 0x2e,
	0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x1b, 0x2e, 0x47, 0x72,
	0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x6f, 0x72, 0x74, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e,
	0x67, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x22, 0x00, 0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x2f,
	0x67, 0x72, 0x61, 0x6e, 0x64, 0x2d, 0x72, 0x65, 0x73, 0x6f, 0x72, 0x74, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grand_resort_proto_rawDescOnce sync.Once
	file_grand_resort_proto_rawDescData = file_grand_resort_proto_rawDesc
)

func file_grand_resort_proto_rawDescGZIP() []byte {
	file_grand_resort_proto_rawDescOnce.Do(func() {
		file_grand_resort_proto_rawDescData = protoimpl.X.CompressGZIP(file_grand_resort_proto_rawDescData)
	})
	return file_grand_resort_proto_rawDescData
}

var file_grand_resort_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_grand_resort_proto_goTypes = []interface{}{
	(*RoomRequestModel)(nil),     // 0: GrandResort.RoomRequestModel
	(*RoomCreationResponse)(nil), // 1: GrandResort.RoomCreationResponse
	(*Room)(nil),                 // 2: GrandResort.Room
	(*RoomList)(nil),             // 3: GrandResort.RoomList
	(*BookingInfo)(nil),          // 4: GrandResort.BookingInfo
	(*BookingConfirm)(nil),       // 5: GrandResort.BookingConfirm
	(*emptypb.Empty)(nil),        // 6: google.protobuf.Empty
}
var file_grand_resort_proto_depIdxs = []int32{
	2, // 0: GrandResort.RoomList.rooms:type_name -> GrandResort.Room
	6, // 1: GrandResort.Reception.createRoomRequestModelc21a7f50:input_type -> google.protobuf.Empty
	0, // 2: GrandResort.Reception.createRoom73950029:input_type -> GrandResort.RoomRequestModel
	6, // 3: GrandResort.Reception.listRooms:input_type -> google.protobuf.Empty
	4, // 4: GrandResort.Reception.bookRoom:input_type -> GrandResort.BookingInfo
	0, // 5: GrandResort.Reception.createRoomRequestModelc21a7f50:output_type -> GrandResort.RoomRequestModel
	1, // 6: GrandResort.Reception.createRoom73950029:output_type -> GrandResort.RoomCreationResponse
	3, // 7: GrandResort.Reception.listRooms:output_type -> GrandResort.RoomList
	5, // 8: GrandResort.Reception.bookRoom:output_type -> GrandResort.BookingConfirm
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grand_resort_proto_init() }
func file_grand_resort_proto_init() {
	if File_grand_resort_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grand_resort_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomRequestModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grand_resort_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomCreationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grand_resort_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Room); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grand_resort_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grand_resort_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookingInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grand_resort_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookingConfirm); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grand_resort_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grand_resort_proto_goTypes,
		DependencyIndexes: file_grand_resort_proto_depIdxs,
		MessageInfos:      file_grand_resort_proto_msgTypes,
	}.Build()
	File_grand_resort_proto = out.File
	file_grand_resort_proto_rawDesc = nil
	file_grand_resort_proto_goTypes = nil
	file_grand_resort_proto_depIdxs = nil
}
