// protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative /path/to/grand-resort.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.22.1
// source: grand-resort.proto

package grand_resort

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Reception_CreateRoomRequestModelc21A7F50_FullMethodName = "/GrandResort.Reception/createRoomRequestModelc21a7f50"
	Reception_CreateRoom73950029_FullMethodName             = "/GrandResort.Reception/createRoom73950029"
	Reception_ListRooms_FullMethodName                      = "/GrandResort.Reception/listRooms"
	Reception_BookRoom_FullMethodName                       = "/GrandResort.Reception/bookRoom"
)

// ReceptionClient is the client API for Reception service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReceptionClient interface {
	CreateRoomRequestModelc21A7F50(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RoomRequestModel, error)
	CreateRoom73950029(ctx context.Context, in *RoomRequestModel, opts ...grpc.CallOption) (*RoomCreationResponse, error)
	ListRooms(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RoomList, error)
	BookRoom(ctx context.Context, in *BookingInfo, opts ...grpc.CallOption) (*BookingConfirm, error)
}

type receptionClient struct {
	cc grpc.ClientConnInterface
}

func NewReceptionClient(cc grpc.ClientConnInterface) ReceptionClient {
	return &receptionClient{cc}
}

func (c *receptionClient) CreateRoomRequestModelc21A7F50(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RoomRequestModel, error) {
	out := new(RoomRequestModel)
	err := c.cc.Invoke(ctx, Reception_CreateRoomRequestModelc21A7F50_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *receptionClient) CreateRoom73950029(ctx context.Context, in *RoomRequestModel, opts ...grpc.CallOption) (*RoomCreationResponse, error) {
	out := new(RoomCreationResponse)
	err := c.cc.Invoke(ctx, Reception_CreateRoom73950029_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *receptionClient) ListRooms(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RoomList, error) {
	out := new(RoomList)
	err := c.cc.Invoke(ctx, Reception_ListRooms_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *receptionClient) BookRoom(ctx context.Context, in *BookingInfo, opts ...grpc.CallOption) (*BookingConfirm, error) {
	out := new(BookingConfirm)
	err := c.cc.Invoke(ctx, Reception_BookRoom_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReceptionServer is the server API for Reception service.
// All implementations must embed UnimplementedReceptionServer
// for forward compatibility
type ReceptionServer interface {
	CreateRoomRequestModelc21A7F50(context.Context, *emptypb.Empty) (*RoomRequestModel, error)
	CreateRoom73950029(context.Context, *RoomRequestModel) (*RoomCreationResponse, error)
	ListRooms(context.Context, *emptypb.Empty) (*RoomList, error)
	BookRoom(context.Context, *BookingInfo) (*BookingConfirm, error)
	mustEmbedUnimplementedReceptionServer()
}

// UnimplementedReceptionServer must be embedded to have forward compatible implementations.
type UnimplementedReceptionServer struct {
}

func (UnimplementedReceptionServer) CreateRoomRequestModelc21A7F50(context.Context, *emptypb.Empty) (*RoomRequestModel, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRoomRequestModelc21A7F50 not implemented")
}
func (UnimplementedReceptionServer) CreateRoom73950029(context.Context, *RoomRequestModel) (*RoomCreationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRoom73950029 not implemented")
}
func (UnimplementedReceptionServer) ListRooms(context.Context, *emptypb.Empty) (*RoomList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRooms not implemented")
}
func (UnimplementedReceptionServer) BookRoom(context.Context, *BookingInfo) (*BookingConfirm, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BookRoom not implemented")
}
func (UnimplementedReceptionServer) mustEmbedUnimplementedReceptionServer() {}

// UnsafeReceptionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReceptionServer will
// result in compilation errors.
type UnsafeReceptionServer interface {
	mustEmbedUnimplementedReceptionServer()
}

func RegisterReceptionServer(s grpc.ServiceRegistrar, srv ReceptionServer) {
	s.RegisterService(&Reception_ServiceDesc, srv)
}

func _Reception_CreateRoomRequestModelc21A7F50_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReceptionServer).CreateRoomRequestModelc21A7F50(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Reception_CreateRoomRequestModelc21A7F50_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReceptionServer).CreateRoomRequestModelc21A7F50(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reception_CreateRoom73950029_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoomRequestModel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReceptionServer).CreateRoom73950029(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Reception_CreateRoom73950029_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReceptionServer).CreateRoom73950029(ctx, req.(*RoomRequestModel))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reception_ListRooms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReceptionServer).ListRooms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Reception_ListRooms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReceptionServer).ListRooms(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reception_BookRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookingInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReceptionServer).BookRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Reception_BookRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReceptionServer).BookRoom(ctx, req.(*BookingInfo))
	}
	return interceptor(ctx, in, info, handler)
}

// Reception_ServiceDesc is the grpc.ServiceDesc for Reception service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Reception_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "GrandResort.Reception",
	HandlerType: (*ReceptionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "createRoomRequestModelc21a7f50",
			Handler:    _Reception_CreateRoomRequestModelc21A7F50_Handler,
		},
		{
			MethodName: "createRoom73950029",
			Handler:    _Reception_CreateRoom73950029_Handler,
		},
		{
			MethodName: "listRooms",
			Handler:    _Reception_ListRooms_Handler,
		},
		{
			MethodName: "bookRoom",
			Handler:    _Reception_BookRoom_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grand-resort.proto",
}
