---
- name: Update and install packages
  hosts: all
  become: yes
  tasks:
    - name: Update all packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install necessary packages
      apt:
        name:
          - wireguard
          - iptables-persistent
          - python3
          - python3-pip
          - python3-dev
          - libkrb5-dev
          - krb5-user
          - jq
        state: present
