services:
  chall:
    image: cybersecnatlab/challenge-jail@sha256:7bf77225063b039960f654307cf5d6f977f892ff548606357a2e8fe8067d0a88
    container_name: no_headache
    restart: unless-stopped
    init: true
    privileged: true
    volumes:
      - './build/no_headache:/home/user/chall:ro'
      - './libs:/home/user/libs:ro'
    ports:
      - '38004:1337'
    environment:
      - 'FLAG=openECSC{__minimal_malloc,__minimal_headache,[random 8]}'
      - 'LOADER=/home/user/libs/ld-linux-x86-64.so.2'
      - 'TIMEOUT=60'
