services:
  asm_provider:
    image: cybersecnatlab/socaz:ubuntu-jammy
    restart: unless-stopped
    command: 'socaz --timeout 120 --bind 31337 --cmd /home/user/chall'
    volumes:
      - './asm_provider/provider:/home/user/chall:ro'
    ports:
      - '38205:31337'
  
  license_checker:
    image: cybersecnatlab/challenge-jail@sha256:8ac55aa6e7fe753a43b9b5a0283113544742798aaef7977eab0e854c476a634a
    restart: unless-stopped
    volumes:
      - './chall/chall:/home/user/chall:ro'
    ports:
      - '38204:1337'
    init: true
    privileged: true
    environment:
      - "FLAG=CCIT{m4yb3_runn1ng_th3_v4lid4t10n_c0d3_0n_my_cl13n7s_l4pt0ps_1sn't_such_4_gr3a7_1dea_04b5e95c}"
      - "FLAG_IN_ENV=true"
      - "FORWARDED_ENV=REMOTE,PORT"
      - "REMOTE=asm_provider"
      - "PORT=31337"
      - "TIMEOUT=120"
      - 'NETWORK=true'
