services:
  chall:
    image: cybersecnatlab/challenge-jail@sha256:a90fb2f6c9b460b8ed559bf78d5cbd084bff11fda5feb863229ec51d58641871
    container_name: triwizard-maze
    restart: unless-stopped
    init: true
    privileged: true
    volumes:
      - './build/triwizard-maze:/home/user/chall:ro'
    ports:
      - '38202:1337'
    environment:
      - 'FLAG=CCIT{C3dr1c_D1gg0ry_w0uld_be_pr0ud_c5f799a0}'
      - 'FLAG_IN_ENV=true'
      - 'RLIMIT_NOFILE=512'
      - 'TEMPDIRS=/tmp'
      - 'TIMEOUT=1200' # 20min
