---
# Load data
- import_playbook: data.yml

# set AD datas ==================================================================================================
- name: DCs AD data configuration
  hosts: dc
  roles:
    - { role: 'ad', tags: 'ad_domain_data' }
  vars:
    hostname: "{{lab.hosts[dict_key].hostname}}"
    domain: "{{lab.hosts[dict_key].domain}}"
    domain_username: "{{domain}}\\{{lab.domains[domain].domain_username}}"
    domain_password: "{{lab.domains[domain].domain_password}}"
    domain_server: "{{lab.hosts[dict_key].hostname}}.{{domain}}"
    ad_users: "{{lab.domains[lab.hosts[dict_key].domain].users}}"
    ad_ou: "{{lab.domains[lab.hosts[dict_key].domain].organisation_units  | default({}) }}"
    ad_groups: "{{lab.domains[lab.hosts[dict_key].domain].groups}}"
    ad_computers: "{{lab.domains[lab.hosts[dict_key].domain].computers | default({}) }}"
    ad_computer_memberships: "{{lab.domains[lab.hosts[dict_key].domain].computer_memberships | default({}) }}"
