---
# Load data
- import_playbook: data.yml

- name: Cleanup
  hosts: domain
  vars:
    domain: "{{lab.hosts[dict_key].domain}}"
    ansible_user: "{{lab.domains[domain].domain_username}}@{{domain | upper}}"
    ansible_password: "{{lab.domains[domain].domain_password}}"
    ansible_winrm_transport: kerberos
  tasks:
    - name: Clear event logs
      ansible.windows.win_powershell:
        script: |
          Get-EventLog -List | ForEach-Object {Clear-EventLog -LogName $_.Log }
