---
# Load data
- import_playbook: data.yml

- name: Make logon sessions
  hosts: domain
  vars:
    logon_sessions: "{{ lab.hosts[dict_key].logon_sessions | default({}) }}"
    domain: "{{lab.hosts[dict_key].domain}}"
    ansible_user: "{{lab.domains[domain].domain_username}}@{{domain | upper}}"
    ansible_password: "{{lab.domains[domain].domain_password}}"
    ansible_winrm_transport: kerberos
  tasks:
    - name: Ensure logon sessions are present
      win_command: whoami
      vars:
        ansible_become: yes
        ansible_become_method: runas
        ansible_become_user: "{{domain}}\\{{item}}"
        ansible_become_password: "{{lab.domains[domain].users[item].password}}"
      with_list: "{{ logon_sessions }}"