---
# Load data
- import_playbook: data.yml

- name: Run scripts
  hosts: domain
  vars:
    scripts: "{{ lab.hosts[dict_key].scripts | default([]) }}"
    domain: "{{lab.hosts[dict_key].domain}}"
    ansible_user: "{{lab.domains[domain].domain_username}}@{{domain | upper}}"
    ansible_password: "{{lab.domains[domain].domain_password}}"
    ansible_winrm_transport: kerberos
  tasks:
    - name: Run scripts
      script: "files/{{ item }}"
      loop: "{{ scripts }}"
      register: script_output

    - name: Show script output
      debug:
        var: script_output